# Generated by Django 4.2.8 on 2024-05-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thrown_movie',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
